decline: 拒绝
allow: 同意
powered_by: 版权所有
search_placeholder: 搜索...
search: 搜索
gdpr_title: 我们使用了第三方Cookies, 为你提供更好的服务体验
gdpr_link: 查看协议
menu: 菜单
previous: 上一页
next: 下一页
go_back_to_home: 返回首页
services: 服务列表
faq: 常见问题
home_title_1: 'The best chinese <span class="text-primary">freight forwarder.</span>'
home_title_2: What shipping methods can we offer
home_title_3: We provide services that you can rely on
home_title_4: Our latest experiences
home_title_5: Frequently Asked Questions
home_description_1: "You need Air, Sea and Rail freight? Our experts are ready to handle your shipment!"
home_description_2: Repellat cum autem consectetur culpa quos mollitia illum qui aspernatur.
home_description_3: Flex is the only saas business platform that lets you run your business on one platform, seamlessly across all digital channels.
about_title_1: Similique fugit cumque rerum ex dolores aliquid ducimus.
about_title_2: We believe in the power of data
about_title_3: Our company
about_title_4: Our vision
about_description_1: Deleniti tempora dolor facere debitis eum. Libero tempora velit non modi provident iusto accusamus autem quam. Quia et sapiente consectetur sint. Ut nulla eos.
about_description_2: Deleniti tempora dolor facere debitis eum. Libero tempora velit non modi provident iusto accusamus autem quam.
about_description_3: Deleniti tempora dolor facere debitis eum. Libero tempora velit non modi provident iusto accusamus autem quam. Quia et sapiente consectetur sint. Ut nulla eos.
about_description_4: Deleniti tempora dolor facere debitis eum. Libero tempora velit non modi provident iusto accusamus autem quam. Quia et sapiente consectetur sint. Ut nulla eos. Ad velit sunt ut culpa pariatur quod at voluptatem molestiae.Deleniti tempora dolor facere debitis eum. Libero tempora velit non modi provident iusto accusamus autem quam. Quia et sapiente consectetur sint. Ut nulla eos.Deleniti tempora dolor facere debitis eum. Libero tempora velit non modi provident iusto accusamus autem quam. Quia et sapiente consectetur sint.
about_item_1_number: 235.000
about_item_2_number: $10m
about_item_3_number: +50.000
about_item_4_number: 3.500
about_item_1_title: Projects completed
about_item_2_title: APR
about_item_3_title: Hours Saved Annually
about_item_4_title: 唯一用户
about_item_1_description: No need to hire specialists for each channel.
about_item_2_description: Track how much money a company just in case
about_item_3_description: Manage many companies, even with different languages.
about_item_4_description: Everyone works the way they want to, on their own schedule.
